//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18213
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Facepunch.Utility;
using UnityEngine;
using System.Collections.Generic;

public class chat : ConsoleSystem
{

	public static List<string> messages = new List<string>();
	public static List<string> users = new List<string>();

	[ConsoleSystem.Admin]
	[ConsoleSystem.Client]
	[ConsoleSystem.Help("Enable or disable chat displaying", "")]
	public static bool enabled = true;
	[ConsoleSystem.Admin]
	public static bool serverlog;
	
	static chat()
	{
	}
	
	[ConsoleSystem.User]
	public static void say(ref ConsoleSystem.Arg arg)
	{
		if (!chat.enabled)
			return;
		string str1 = String.QuoteSafe(arg.argUser.user.Displayname);
		string str2 = String.QuoteSafe(arg.GetString(0, "text"));

		if(str2 != null && str2.Length > 1 && str2.Substring(1, 1).Equals("/")) {
			rustpp.handleCommand(ref arg);
		} else {

			if (chat.serverlog)
				Debug.Log((object) ("[YES HIJACKED CHAT:] " + str1 + ":" + str2));

			messages.Add (str2);
			users.Add (str1);
			ConsoleNetworker.Broadcast("chat.add " + str1 + " " + str2);
		}
	}
}
